
services:
  # BaSyx Dependencies
  basyx-mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    networks:
      - basyx-ui-dev

  basyx-aas-registry:
    image: eclipsebasyx/aas-registry-log-mongodb:2.0.0-SNAPSHOT
    pull_policy: never
    ports:
      - "8101:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://admin:admin@basyx-mongodb:27017
      - BASYX_CORS_ALLOWED-ORIGINS=http://localhost:3000
      - SERVER_PORT=8080
    depends_on:
      - basyx-mongodb
    restart: unless-stopped
    networks:
      - basyx-ui-dev

  basyx-submodel-registry:
    image: eclipsebasyx/submodel-registry-log-mongodb:2.0.0-SNAPSHOT
    pull_policy: never
    ports:
      - "8102:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://admin:admin@basyx-mongodb:27017
      - BASYX_CORS_ALLOWED-ORIGINS=http://localhost:3000
      - SERVER_PORT=8080
    depends_on:
      - basyx-mongodb
    restart: unless-stopped
    networks:
      - basyx-ui-dev

  basyx-aas-repository:
    image: eclipsebasyx/aas-repository:2.0.0-SNAPSHOT
    ports:
      - "8103:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://admin:admin@basyx-mongodb:27017
      - BASYX_CORS_ALLOWED-ORIGINS=http://localhost:3000
      - SPRING_PROFILES_ACTIVE=default
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=8080
    restart: unless-stopped
    networks:
      - basyx-ui-dev

  basyx-submodel-repository:
    image: eclipsebasyx/submodel-repository:2.0.0-SNAPSHOT
    ports:
      - "8104:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://admin:admin@basyx-mongodb:27017
      - BASYX_CORS_ALLOWED-ORIGINS=http://localhost:3000
      - SPRING_PROFILES_ACTIVE=default
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=8080
    restart: unless-stopped
    networks:
      - basyx-ui-dev

  basyx-cd-repository:
    image: eclipsebasyx/conceptdescription-repository:2.0.0-SNAPSHOT-8d0df27
    ports:
      - "8105:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://admin:admin@basyx-mongodb:27017
      - BASYX_CORS_ALLOWED-ORIGINS=http://localhost:3000
      - SPRING_PROFILES_ACTIVE=default
      - SERVER_ADDRESS=0.0.0.0
      - SERVER_PORT=8080
    restart: unless-stopped
    networks:
      - basyx-ui-dev

  # BaSyx WebUI
  basyx-ui:
    image: eclipsebasyx/aas-gui:latest
    build:
      context: ./SOURCE/aas-web-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./SOURCE/aas-web-ui:/app/src
    command: npm run dev
    environment:
      - AAS_REGISTRY_PATH=http://localhost:8101/shell-descriptors
      - SUBMODEL_REGISTRY_PATH=http://localhost:8102/submodel-descriptors
      - AAS_REPO_PATH=http://localhost:8103/shells
      - SUBMODEL_REPO_PATH=http://localhost:8104/submodels
      - CD_REPO_PATH=http://localhost:8105/concept-descriptions
    depends_on:
      - basyx-aas-registry
      - basyx-submodel-registry
      - basyx-aas-repository
      - basyx-submodel-repository
      - basyx-cd-repository
    restart: unless-stopped
    networks:
      - basyx-ui-dev

networks:
  basyx-ui-dev:

volumes:
  mongo-data: