version: "3.8"

services:
  swagger:
    image: swaggerapi/swagger-editor
    ports:
      - "8081:8080"
    volumes:
      - ./EXECUTABLE/swagger/din18222.yaml:/tmp/din18222.yaml
    environment:
      SWAGGER_FILE: /tmp/din18222.yaml
    networks:
      - basyx-ui-dev

networks:
  basyx-ui-dev: