version: "3.8"

services:
  swagger:
    build: .
    image: swe_team-6_basyx-ui-swagger:latest
    ports:
      - "8081:8080"
    restart: unless-stopped
    networks:
      - basyx-ui

networks:
  basyx-ui: