server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health,info

spring:
  data:
    mongodb:
      uri: mongodb://dppUser:dppPass@localhost:27017/basyx_dpp?authSource=admin
