name: Deploy Swagger Specification

on:
  workflow_dispatch:
  pull_request_review:
    types: [submitted]
    branches:
      - main

jobs:
  deploy-swagger:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request_review' && contains(github.event.pull_request.body, '+swagger'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Copy OpenAPI file via scp
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: deploy
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "/EXECUTABLE/swagger/din18222.yaml"
          target: "/srv/swe-basyx/swagger-spec/"

      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        env:
          GHCR_USERNAME: ${{ secrets.GHCR_USERNAME }}
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: deploy
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: GHCR_USERNAME,GHCR_TOKEN
          script: |
            /srv/swe-basyx/load_swagger.sh